### ISSUE TITLE
Learning graph embeddings for the syntactic graph

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/triframes#1] opened 2018-06-11 13:15 UTC
1. Input file of tripes in the format ``verb subject object score``, e.g.: 

```
take#VB event   place   112493.0
see#VB  x       frame   56300.0
have#VB anyone  idea    56202.0
offer#VB        Expedia airfare 56180.0
provide#VB      invention       method  53138.0
have#VB anyone  experience      48864.0
receive#VB      family  friend  47644.0
do#VB   people  thing   47483.0
have#VB student opportunity     45680.0
take#VB meeting place   44599.0
use#VB  Gemvara material        42037.0
show#VB FIG.    view    41693.0
illustrate#VB   FIG.    embodiment      37872.0
have#VB people  problem 37540.0
take#VB change  place   37195.0
``` 

- pruned: http://panchenko.me/data/joint/verbs/cc16malt/vso-1.3m-pruned-strict.csv.gz
- full: http://panchenko.me/data/joint/verbs/cc16malt/vso-25m-pruned.csv.gz

2. Construct the graph of triples via triple co-occurrences. If two triples have the two common elements (e.g. subject and verb OR verb and object), then they are connected. 

     Alternatively, If two triples have only one common element (e.g. common subject) then the weight is one. 

3. Use deepWalk, node2vec, and path2vec to learn vector representations of these triples. Use various meta-parameters for each approach, e.g. the number of dimensions and walks. 

4. Evaluate the obtained triple representations on the task of frame induction by running the evaluation code available in this repository using the methodology described in this paper: https://arxiv.org/abs/1805.04715 (published at ACL'2018, https://acl2018.org/).

**Comment by alexteua** [comment] 2018-07-15 12:14
I've checked embeddings obtained with DeepWalk by loading to gensim and checking most similar nodes, it looks like:

similar to:  have#VB people time
--------------
have#VB people depression 0.7461773157119751
have#VB people address 0.7298743724822998
have#VB people monopoly 0.7279400825500488
have#VB people brain 0.7251932621002197
have#VB people score 0.7251231074333191


similar to:  provide#VB provider information
--------------
provide#VB image information 0.9872413873672485
provide#VB change information 0.987193763256073
provide#VB column information 0.9869943261146545
provide#VB publication information 0.9869118928909302
provide#VB booklet information 0.9863284230232239

**Comment by alexteua** [comment] 2018-07-15 12:16
Looks like we can continue with running more experiments on this graph

**Comment by alexanderpanchenko** [comment] 2018-07-15 13:56
looks indeed reasonable - please provide a few more examples here to get a
better understanding (just a few more triples and a bit more nearest
neighbours per triple).

good to go in my mind - just proceed as planned.

**Comment by alexteua** [comment] 2018-07-15 20:42
similar to:  highlight#VB report problem
--------------
highlight#VB report fact 0.9538995623588562
highlight#VB report importance 0.9202446341514587
highlight#VB report need 0.9141565561294556
highlight#VB study fact 0.8908078074455261
underscore#VB report need 0.8627906441688538
highlight#VB study need 0.8606923818588257
emphasize#VB report need 0.8565777540206909
highlight#VB study importance 0.854476273059845
stress#VB report need 0.8541354537010193
emphasize#VB report importance 0.8476148843765259

similar to:  answer#VB story question
--------------
answer#VB manager question 0.9966793060302734
answer#VB time question 0.9966354966163635
answer#VB candidate question 0.9964892864227295
answer#VB site question 0.9964324831962585
answer#VB scientist question 0.9964265823364258
answer#VB team question 0.9963186979293823
answer#VB Minister question 0.9963048696517944
answer#VB Paul question 0.9962888956069946
answer#VB research question 0.9962843656539917
answer#VB Jesus question 0.9962024092674255

**Comment by alexteua** [comment] 2018-07-15 20:45
similar to:  wear#VB woman burqa
--------------
wear#VB woman bikini 0.9982713460922241
wear#VB woman veil 0.9982062578201294
wear#VB woman pants 0.9981944561004639
wear#VB woman scarf 0.9980823397636414
wear#VB woman clothing 0.9980330467224121
wear#VB woman blouse 0.9979761838912964
wear#VB woman bra 0.9979567527770996
wear#VB woman outfit 0.9979463219642639
wear#VB woman hijab 0.9979447722434998
wear#VB woman coat 0.9979429244995117

similar to:  feature#VB knife blade
--------------
feature#VB Knife blade 0.9742035269737244
have#VB knife blade 0.9537492990493774
have#VB knife edge 0.7106331586837769
have#VB knife handle 0.6131154894828796
have#VB blade edge 0.554728627204895
have#VB voice edge 0.5477390885353088
have#VB Democrats edge 0.47338515520095825
have#VB plate edge 0.4549257159233093
have#VB Republicans edge 0.45163947343826294
have#VB Romney edge 0.4388987720012665

**Comment by alexteua** [comment] 2018-07-15 20:52
similar to:  address#VB comment issue
--------------
address#VB member issue 0.995779812335968
address#VB candidate issue 0.9954516291618347
address#VB discussion issue 0.9953857660293579
address#VB workshop issue 0.9953724145889282
address#VB legislation issue 0.9953103065490723
address#VB conference issue 0.9952685832977295
address#VB one issue 0.9952408671379089
address#VB Commission issue 0.9950791597366333
address#VB Circuit issue 0.9950239062309265
address#VB leader issue 0.9950180053710938

similar to:  catch#VB thing fire
--------------
catch#VB idea fire 0.9952883124351501
catch#VB car fire 0.9951303005218506
catch#VB plane fire 0.9951239228248596
catch#VB tree fire 0.9947503805160522
catch#VB house fire 0.994671642780304
catch#VB home fire 0.9944249987602234
catch#VB clothing fire 0.9942343831062317
catch#VB ship fire 0.994118332862854
catch#VB team fire 0.9940105676651001
catch#VB vehicle fire 0.9939444065093994

**Comment by alexanderpanchenko** [comment] 2018-07-16 14:11
thanks - looks quite reasonable. please generate now various versions of
the embeddings and then we can perform their evaluation in the context of
the frame induction task as done in the referenced paper above (which
@dustalov is currently presenting in Melbourne).

**Comment by alexanderpanchenko** [comment] 2018-07-30 08:43
Please send links to the pre-computed word vectors (on the servers).

**Comment by alexteua** [comment] 2018-07-30 08:54
on ltcpu1: /home/6oliinyk/triframes_results

**Comment by alexanderpanchenko** [comment] 2018-07-30 08:54
ok thanks

**Comment by alexanderpanchenko** [comment] 2018-08-15 09:45
@dustalov Here is the updated version of the data which you can use.

The list of all embeddings for 100k triples: https://docs.google.com/spreadsheets/d/1CCwLjWetFuMwl3qgO8yQXVpbbxlRWDlIbqoNrVjB6B8/edit?usp=sharing 

The data are stored here: http://ltdata1.informatik.uni-hamburg.de/frames/

**Comment by dustalov** [comment] 2018-08-16 16:17
I have access only to `ltnode1d` and `farnsworth`. Please release the rest of the data including the id to triple mappings for each graph.

**Comment by dustalov** [comment] 2018-08-16 16:18
I have access only to `ltnode1d` and `ltcpu3`. Please release the rest of the data including the id to triple mappings for each graph.

**Comment by alexanderpanchenko** [comment] 2018-08-16 16:19
http://ltdata1.informatik.uni-hamburg.de/frames/

**Comment by dustalov** [comment] 2018-08-16 16:23
I have seen this link a few comments above, thank you. I am talking about the files which names are `id_to_name.pkl` as stated in https://github.com/uhh-lt/triframes/blob/master/graph_embeddings/generate_graph.py.

**Comment by alexanderpanchenko** [comment] 2018-08-16 16:25
@alexteua please provide the path to pkl files - I will put them online.

**Comment by alexanderpanchenko** [comment] 2018-08-16 16:27
It may be also you do not need the pkl files - the embeddings should be self contained.

**Comment by dustalov** [comment] 2018-08-16 16:33
No. There are some integer identifiers instead of triples in the vector files. There is no reliable approach to map these identifiers to the actual triples.

**Comment by alexanderpanchenko** [comment] 2018-08-16 16:35
@alexteua please generate embeddings which contain actual triples, not integer ids.

**Comment by alexteua** [comment] 2018-08-17 21:10
@alexanderpanchenko @dustalov 
In every directory with generated embeddings there are 2 subdirectories now: num_ids and triple_ids. First one contains embeddings which you saw, second one with triples instead of numerical ids.  I also committed script which can do such a replacement.
In triframes_results directory you can also find id_to_name_full.pkl  and id_to_name_pruned.pkl which are dictionaries for graphs based on full and pruned datasets accordingly.

**Comment by alexanderpanchenko** [comment] 2018-08-18 19:50
Thanks.

**Comment by alexanderpanchenko** [comment] 2018-08-19 20:40
@dustalov I've updated the files. Please check! http://ltdata1.informatik.uni-hamburg.de/frames/

**Comment by dustalov** [comment] 2018-08-20 10:24
Awesome, thank you both!

**Comment by alexteua** [comment] 2018-08-20 16:54
I will upload more embeddings soon

**Comment by alexanderpanchenko** [comment] 2018-08-20 19:50
Thanks. Please try implementing the graph generation procedure using a sparse adjacency matrix which will make it possible to store graphs from more than 100k triples.

**Comment by alexteua** [comment] 2018-08-28 08:38
I've uploaded more embeddings done for:
- deepwalk, full dataset, first 100K
- deepwalk, pruned dataset, first 1M

Google doc is updated with configurations

**Comment by alexteua** [comment] 2018-08-28 08:42
node2vec implementation is going to out of memory error while generating embeddings for latest mentioned categories. 
It accepts only edgelist as input format, which is more redundant than adjlist.

**Comment by alexteua** [comment] 2018-08-28 08:44
Please let me know if we need embeddings with some specific configurations to generate

**Comment by alexanderpanchenko** [comment] 2018-08-28 08:44
Thanks! Out of memory is on which machine? Ltcpu1?

**Comment by alexteua** [comment] 2018-08-28 08:46
Yes, Ltcpu1. I just see "Killed" output from running script

**Comment by alexanderpanchenko** [comment] 2018-08-28 08:46
Could you provide please some nearest  neighbors for the two mentioned new
models?

**Comment by alexanderpanchenko** [comment] 2018-08-28 08:48
Please run again and check the memory usage using htop.  The machine has
256 gb of ram.

**Comment by alexteua** [comment] 2018-08-28 09:05
for one of the embeddings within "deepwalk, full dataset, first 100K" category

similar to:  eat#VB PERSON cookie
--------------
eat#VB PERSON cookie 0.961711049079895
eat#VB PERSON cereal 0.9581553339958191
eat#VB PERSON portion 0.9558544158935547
eat#VB PERSON plate 0.9556226134300232
eat#VB PERSON healthy 0.9554531574249268
eat#VB PERSON dessert 0.9551925659179688
eat#VB PERSON fruit 0.9550948739051819
eat#VB PERSON pizza 0.9548265933990479
eat#VB PERSON fruit 0.9545609951019287
eat#VB PERSON pizza 0.9542282223701477

similar to:  read#VB PERSON autobiography
--------------
read#VB PERSON verse 0.9585568904876709
read#VB PERSON comic 0.9577409625053406
read#VB PERSON manga 0.9567180275917053
read#VB PERSON poem 0.9564070105552673
read#VB PERSON excerpt 0.9562754034996033
read#VB PERSON novel 0.9559537768363953
read#VB PERSON newspaper 0.9558944702148438
read#VB PERSON trilogy 0.9556835293769836
read#VB PERSON translation 0.9554949998855591
read#VB PERSON ebook 0.955351710319519

similar to:  have#VB THING image
--------------
have#VB THING frame 0.9377962946891785
have#VB THING acid 0.936640739440918
have#VB THING field 0.9364444017410278
have#VB THING beach 0.9363809823989868
have#VB THING reference 0.9361435770988464
have#VB THING restaurant 0.9358288049697876
have#VB THING discussion 0.9358265399932861
have#VB THING inhabitant 0.9356974363327026
have#VB THING pad 0.9350844621658325
have#VB THING lock 0.9350626468658447

**Comment by alexanderpanchenko** [comment] 2018-08-28 09:07
Could you please show 100 nearest neighbors as well for these triples?

**Comment by alexanderpanchenko** [comment] 2018-08-28 09:08
eat#VB PERSON pizza 0.9548265933990479
eat#VB PERSON fruit 0.9545609951019287
eat#VB PERSON pizza 0.9542282223701477

Why there are duplicates?

**Comment by alexteua** [comment] 2018-08-28 09:16
ok, I will commit some examples for 100 nearest neighbors to the repo, to keep the discussion cleaner.
regarding duplicates currently I have no idea, will check the dataset if the issue is there.

**Comment by alexanderpanchenko** [comment] 2018-08-28 15:35
Ok. Thanks

**Comment by alexanderpanchenko** [comment] 2018-08-28 15:43
You can upload to Google drive or Dropbox samples of nearest neighbors and
post the link here...

**Comment by alexteua** [comment] 2018-09-07 17:10
here are some samples of nearest neighbors:
https://drive.google.com/drive/folders/1mqgxIyHswPFOKH9FzlTdfaUjO3z6vnP1?usp=sharing

**Comment by alexanderpanchenko** [comment] 2018-09-07 17:26
Thanks, can you also generate the same for 'eat#VB PERSON pizza' and 'read#VB PERSON autobiography'?

What about the duplicates? Do you have any ideas why this happens?

**Comment by alexteua** [comment] 2018-09-07 17:27
I checked the dataset and duplicates are there.
eat#VB  PERSON  pizza  3131.0
eat#VB  PERSON  pizza  1593.0
eat#VB  PERSON  pizza  1117.0

**Comment by alexanderpanchenko** [comment] 2018-09-07 17:35
Ok, I have to check that. I think this the result of some normalisation
(like lowercasing). Please then sum up the frequencies before the training
and release a file in the same format without duplicates.

**Comment by alexteua** [comment] 2018-09-08 06:57
do you mean to retrain embeddings? There are various hyperparameter combinations, which one to pick up? I guess to retrain all of them will take a lot of time

**Comment by alexanderpanchenko** [comment] 2018-09-08 09:26
We do not know yet which ones are the best. If this is just machine time
that's not an issue - just launch maybe a bash script with all the
combinations and let it run.

**Comment by alexteua** [comment] 2018-09-17 20:43
Just some information on duplicates in the input data:

pruned: http://panchenko.me/data/joint/verbs/cc16malt/vso-1.3m-pruned-strict.csv.gz
here is just about 1% of duplicates

full: http://panchenko.me/data/joint/verbs/cc16malt/vso-25m-pruned.csv.gz
here is about 40% of duplicates

**Comment by alexanderpanchenko** [comment] 2018-09-17 20:44
interesting, thanks

**Closed as completed** 2020-02-23 19:38 UTC
Labels: enhancement
